global class BusObjRecommendationInputRepresentation {
	global String acceptanceLabel;
	global ConnectApi.ActionInfoInputRepresentation actionInfo;
	global String businessObjectiveId;
	global String description;
	global String domain;
	global String externalState;
	global String iconName;
	global String imageId;
	global String name;
	global String recommendationId;
	global String rejectionLabel;
	global String score;
	global ConnectApi.StateInputRepresentation state;
	global BusObjRecommendationInputRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}