global class RecRepresentation {
	global String acceptanceLabel;
	global ConnectApi.ActionInfoOutputRepresentation actionInfo;
	global String businessObjectiveId;
	global String description;
	global String domain;
	global String externalName;
	global String externalState;
	global String flowName;
	global String iconName;
	global String id;
	global String imageId;
	global String imageUrl;
	global String name;
	global String rejectionLabel;
	global Integer score;
	global ConnectApi.StateOutputRepresentation state;
	global ConnectApi.TargetActionOutputRepresentation targetAction;
	global RecRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}