global class UnifiedKnowledgeConnector {
	global List<ConnectApi.UnifiedKnowledgeConnectorAuthParam> authenticationParameters;
	global String id;
	global List<String> includedSources;
	global String name;
	global String rtaField;
	global String source;
	global String status;
	global Integer totalArticles;
	global UnifiedKnowledgeConnector() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}